# Generated by Django 5.0.4 on 2024-05-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(to='booking.service'),
        ),
    ]
