# Generated by Django 5.0.4 on 2024-05-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_serviceprovider_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='services',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service',
            field=models.ManyToManyField(to='booking.service'),
        ),
    ]
