# Generated by Django 5.0.4 on 2024-05-07 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_serviceprovider_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
