# Generated by Django 5.0.4 on 2024-05-07 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
