# Generated by Django 5.0.4 on 2024-05-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
